<template>
  <router-view />
</template>

<script>
export default {
  created() {
    if (!localStorage.getItem("proposedIniciatives"))
      localStorage.setItem(
        "proposedIniciatives",
        JSON.stringify([
          {
            photo: "aulYog.png",
            name: "Marta Ferreira",
            birthDate: "1989-05-12",
            email: "marta.ferreira@gmail.com",
            local: "Porto",
            maxParticipants: 20,
            minParticipants: 10,
            objective: "Juntar a comunidade local",
            status: "pendente",
            targetAudience: "Adultos",
            telNumber: "912345678",
            theme: "Aula de Yoga",
            date: "2024-07-01",
            participantsAssociated: 0
          },
          {
            photo: "corrSol.png",
            name: "Luís Silva",
            birthDate: "1992-08-23",
            email: "lmpsilva8@gmail.com",
            local: "Lisboa",
            maxParticipants: 35,
            minParticipants: 15,
            objective: "Promover a saúde física e angariar fundos",
            status: "pendente",
            targetAudience: "Todos",
            telNumber: "912345789",
            theme: "Corrida Solidária",
            date: "2024-07-25",
            participantsAssociated: 0
          },
          {
            photo: "aulZum.png",
            name: "Sofia Carvalho",
            birthDate: "1987-03-17",
            email: "sofia.carvalho@gmail.com",
            local: "Faro",
            maxParticipants: 30,
            minParticipants: 20,
            objective: "Promover aula de zumba ao ar livre",
            status: "pendente",
            targetAudience: "Jovens e Adultos",
            telNumber: "912345890",
            theme: "Aula de Zumba",
            date: "2024-07-05",
            participantsAssociated: 0
          },
          {
            photo: "volPrai.png",
            name: "Luís Silva",
            birthDate: "1994-11-28",
            email: "lmpsilva8@gmail.com",
            local: "Aveiro",
            maxParticipants: 15,
            minParticipants: 8,
            objective: "Realizar um torneio de vôlei de praia",
            status: "pendente",
            targetAudience: "Jovens",
            telNumber: "912345678",
            theme: "Torneio de Vôlei de Praia",
            date: "2024-07-20",
            participantsAssociated: 0
          },
          {
            photo: "camMati.png",
            name: "Ana Santos",
            birthDate: "1990-07-05",
            email: "ana.santos@gmail.com",
            local: "Coimbra",
            maxParticipants: 20,
            minParticipants: 10,
            objective: "Organizar uma caminhada matinal no parque",
            status: "pendente",
            targetAudience: "Adultos",
            telNumber: "912345987",
            theme: "Caminhada Matinal",
            date: "2024-08-18",
            participantsAssociated: 0
          },
          {
            photo: "ciclUrb.png",
            name: "Luís Pereira",
            birthDate: "1985-02-19",
            email: "luis.pereira@gmail.com",
            local: "Braga",
            maxParticipants: 25,
            minParticipants: 15,
            objective: "Promover a prática de ciclismo urbano",
            status: "pendente",
            targetAudience: "Todos",
            telNumber: "912345678",
            theme: "Ciclismo Urbano",
            date: "2024-07-19",
            participantsAssociated: 0
          },
          {
            photo: "aulPil.png",
            name: "Luís Silva",
            birthDate: "1993-09-11",
            email: "lmpsilva8@gmail.com",
            local: "Évora",
            maxParticipants: 20,
            minParticipants: 10,
            objective: "Realizar aulas de pilates ao ar livre",
            status: "rejeitada",
            targetAudience: "Adultos",
            telNumber: "912345789",
            theme: "Aulas de Pilates",
            date: "2024-05-23",
            participantsAssociated: 0
          },
          {
            photo: "corrNat.png",
            name: "Luís Silva",
            birthDate: "1988-04-24",
            email: "lmpsilva8@gmail.com",
            local: "Guarda",
            maxParticipants: 15,
            minParticipants: 8,
            objective: "Organizar uma corrida na natureza",
            status: "rejeitada",
            targetAudience: "Jovens e Adultos",
            telNumber: "912345890",
            theme: "Corrida de Orientação",
            date: "2024-04-29",
            participantsAssociated: 0
          },
          {
            photo: "aulCross.png",
            name: "Inês Carreira",
            birthDate: "1996-06-14",
            email: "ines.carreira@gmail.com",
            local: "Setúbal",
            maxParticipants: 30,
            minParticipants: 20,
            objective: "Promover aulas de crossfit",
            status: "pendente",
            targetAudience: "Adultos",
            telNumber: "912345678",
            theme: "Aula de Crossfit",
            date: "2024-07-30",
            participantsAssociated: 0
          },
          {
            photo: "nat.png",
            name: "Diogo Rodrigues",
            birthDate: "1991-12-30",
            email: "diogo.rodrigues@gmail.com",
            local: "Viseu",
            maxParticipants: 25,
            minParticipants: 15,
            objective: "Realizar uma competição de natação",
            status: "pendente",
            targetAudience: "Jovens",
            telNumber: "912345789",
            theme: "Competição de Natação",
            date: "2024-07-24",
            participantsAssociated: 0
          },
          {
            photo: "treinoFun.png",
            name: "Teresa Sousa",
            birthDate: "1987-08-02",
            email: "teresa.sousa@gmail.com",
            local: "Funchal",
            maxParticipants: 20,
            minParticipants: 10,
            objective: "Organizar uma sessão de treino",
            status: "rejeitada",
            targetAudience: "Adultos",
            telNumber: "912345890",
            theme: "Treino Funcional",
            date: "2024-06-01",
            participantsAssociated: 0
          },
          {
            photo: "aulDan.png",
            name: "Beatriz Silva",
            birthDate: "1990-03-28",
            email: "beatriz.silva@gmail.com",
            local: "Porto",
            maxParticipants: 15,
            minParticipants: 8,
            objective: "Realizar aula de dança",
            status: "pendente",
            targetAudience: "Adultos",
            telNumber: "912345678",
            theme: "Aula de Dança de Salão",
            date: "2024-07-19",
            participantsAssociated: 0
          },
          {
            photo: "corr.png",
            name: "Hugo Fernandes",
            birthDate: "1986-11-15",
            email: "hugo.fernandes@gmail.com",
            local: "Lisboa",
            maxParticipants: 20,
            minParticipants: 10,
            objective: "Organizar uma sessão de corrida",
            status: "rejeitada",
            targetAudience: "Todos",
            telNumber: "912345789",
            theme: "Treino de Corrida",
            date: "2024-07-01",
            participantsAssociated: 0
          },
          {
            photo: "escRoch.png",
            name: "Luís Silva",
            birthDate: "1995-05-20",
            email: "lmpsilva8@gmail.com",
            local: "Faro",
            maxParticipants: 25,
            minParticipants: 15,
            objective: "Promover uma aula de escalada",
            status: "pendente",
            targetAudience: "Jovens e Adultos",
            telNumber: "912345890",
            theme: "Aula de Escalada",
            date: "2024-07-23",
            participantsAssociated: 0
          },
          {
            photo: "corrNot.png",
            name: "Pedro Santos",
            birthDate: "1988-09-10",
            email: "pedro.santos@gmail.com",
            local: "Aveiro",
            maxParticipants: 30,
            minParticipants: 20,
            objective: "Realizar uma corrida solidária",
            status: "pendente",
            targetAudience: "Todos",
            telNumber: "912345678",
            theme: "Corrida Noturna Solidária",
            date: "2024-08-01",
            participantsAssociated: 0
          },
          {
            photo: "remo.png",
            name: "Inês Oliveira",
            birthDate: "1993-12-05",
            email: "ines.oliveira@gmail.com",
            local: "Coimbra",
            maxParticipants: 15,
            minParticipants: 8,
            objective: "Organizar uma aula de remo",
            status: "rejeitada",
            targetAudience: "Jovens e Adultos",
            telNumber: "912345789",
            theme: "Introdução ao Remo",
            date: "2024-09-14",
            participantsAssociated: 0
          },
        ])
      );

    if (!localStorage.getItem("proposedCollaborators"))
      localStorage.setItem(
        "proposedCollaborators",
        JSON.stringify([
          {
            photo: "ruiCos.png",
            name: "Rui Costa",
            birthDate: "2000-04-29",
            telNumber: "938477193",
            address: "Rua das Flores",
            email: "ruicosta2000@gmail.com",
            check: false,
          },
          {
            photo: "antSil.png",
            name: "António Silva",
            birthDate: "2003-01-09",
            telNumber: "918383992",
            address: "Avenida dos Campos",
            email: "asilva03@gmail.com",
            check: false,
          },
          {
            photo: "joaLop.png",
            name: "Joana Lopes",
            birthDate: "1999-12-19",
            telNumber: "940149282",
            address: "Rua do Sol Nascente",
            email: "joanalopes19@gmail.com",
            check: false,
          },
          {
            photo: "marfer.png",
            name: "Maria Fernandes",
            birthDate: "1995-06-22",
            telNumber: "937485621",
            address: "Alameda das Palmeiras",
            email: "mfernandes95@gmail.com",
            check: false,
          },
          {
            photo: "carPer.png",
            name: "Carlos Pereira",
            birthDate: "1988-03-15",
            telNumber: "912345678",
            address: "Travessa do Mar",
            email: "cpereira88@gmail.com",
            check: false,
          },
          {
            photo: "anaSou.png",
            name: "Ana Sousa",
            birthDate: "2001-11-05",
            telNumber: "923456789",
            address: "Rua das Acácias",
            email: "anasousa01@gmail.com",
            check: false,
          },
          {
            photo: "paulMend.png",
            name: "Paulo Mendes",
            birthDate: "1993-08-30",
            telNumber: "934567890",
            address: "Avenida da Liberdade",
            email: "pmendes93@gmail.com",
            check: false,
          },
        ])
      );

    if (!localStorage.getItem("backofficeEmails"))
      localStorage.setItem(
        "backofficeEmails",
        JSON.stringify([
          "lmpsilva8@gmail.com",
          "andreyunosilva@gmail.com",
          "marcoalexandre200321@gmail.com",
          "limap2625@gmail.com",
          "angelofariavsc88@gmail.com",
          "gugalima.43r@gmail.com",
        ])
      );

    if (!localStorage.getItem("materials"))
      localStorage.setItem(
        "materials",
        JSON.stringify([
          {
            photo: "bola.png",
            name: "Bola de Futebol",
            description: "Tamanho padrão",
            quantity: 20,
            check: false,
          },
          {
            photo: "sapatilhasCorrida.png",
            name: "Sapatilhas de Corrida",
            description: "Par de sapatilhas de corrida para adultos",
            quantity: 15,
            check: false,
          },
          {
            photo: "fitaMe.png",
            name: "Fita Métrica",
            description: "Fita métrica de 2 metros",
            quantity: 10,
            check: false,
          },
          {
            photo: "garrafaA.png",
            name: "Garrafa de Água",
            description: "Garrafa de água reutilizável de 0.5L",
            quantity: 30,
            check: false,
          },
          {
            photo: "pratosDescartaveis.png",
            name: "Pratos Descartáveis",
            description: "Pacote com 50 pratos descartáveis biodegradáveis",
            quantity: 30,
            check: false,
          },
          {
            photo: "barraCereais.png",
            name: "Barras de Cereal",
            description: "Caixa com 20 barras de cereal",
            quantity: 35,
            check: false,
          },
          {
            photo: "fitaAlongamento.png",
            name: "Fita de Alongamento",
            description: "Fita de alongamento de 2 metros",
            quantity: 15,
            check: false,
          },
          {
            photo: "cronometro.png",
            name: "Cronômetro",
            description: "Cronômetro digital",
            quantity: 10,
            check: false,
          },
          {
            photo: "kit.png",
            name: "Kit de Primeiros Socorros",
            description: "Kit básico para emergências",
            quantity: 8,
            check: false,
          },
        ])
      );

    if (!localStorage.getItem("collaborators"))
      localStorage.setItem(
        "collaborators",
        JSON.stringify([
          {
            photo: "LuSi.png",
            name: "Luís Silva",
            birthDate: "2003-08-18",
            telNumber: "910203040",
            address: "Rua das Palmeiras",
            email: "lmpsilva8@gmail.com",
            check: false,
          },
          {
            photo: "carolFer.png",
            name: "Carolina Fernandes",
            birthDate: "1990-09-20",
            telNumber: "917273849",
            address: "Avenida do Mar",
            email: "carolina.fernandes@gmail.com",
            check: false,
          },
          {
            photo: "andSan.png",
            name: "André Santos",
            birthDate: "1988-02-05",
            telNumber: "919293949",
            address: "Travessa dos Cedros",
            email: "andre.santos@gmail.com",
            check: false,
          },
          {
            photo: "mariOli.png",
            name: "Mariana Oliveira",
            birthDate: "1995-11-10",
            telNumber: "925354647",
            address: "Rua da Praia",
            email: "mariana.oliveira@gmail.com",
            check: false,
          },
          {
            photo: "luCost.png",
            name: "Luís Costa",
            birthDate: "1986-04-03",
            telNumber: "932405060",
            address: "Avenida das Árvores",
            email: "luis.costa@gmail.com",
            check: false,
          },
          {
            photo: "beSou.png",
            name: "Beatriz Sousa",
            birthDate: "1992-09-12",
            telNumber: "937485960",
            address: "Travessa da Fonte",
            email: "beatriz.sousa@gmail.com",
            check: false,
          },
          {
            photo: "paulMart.png",
            name: "Paulo Martins",
            birthDate: "1983-06-07",
            telNumber: "919293940",
            address: "Rua das Oliveiras",
            email: "paulo.martins@gmail.com",
            check: false,
          },
          {
            photo: "margRodri.png",
            name: "Margarida Rodrigues",
            birthDate: "1987-03-30",
            telNumber: "919293950",
            address: "Avenida da Praça",
            email: "margarida.rodrigues@gmail.com",
            check: false,
          },
          {
            photo: "ricFer.png",
            name: "Ricardo Fernandes",
            birthDate: "1995-10-18",
            telNumber: "919293960",
            address: "Rua do Sol",
            email: "ricardo.fernandes@gmail.com",
            check: false,
          },
          {
            photo: "catCos.png",
            name: "Catarina Costa",
            birthDate: "1989-07-22",
            telNumber: "919293970",
            address: "Avenida da Liberdade",
            email: "catarina.costa@gmail.com",
            check: false,
          },
        ])
      );

    if (!localStorage.getItem("iniciatives"))
      localStorage.setItem(
        "iniciatives",
        JSON.stringify([
          {
            photo: "aulYog.png",
            name: "Luís Silva",
            birthDate: "1989-05-12",
            telNumber: "912345678",
            theme: "Aula de Yoga",
            local: "Porto",
            targetAudience: "Adultos",
            minParticipants: 10,
            maxParticipants: 20,
            objective: "Realizar aula de yoga para os locais",
            date: "2024-07-01",
            status: "aceite",
            email: "lmpsilva8@gmail.com",
            expectedDuration: "20",
            professionals: [
              {
                name: "Dionísio Lopes",
                role: "Professor de Yoga",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "catCos.png",
                name: "Catarina Costa",
                birthDate: "1989-07-22",
                telNumber: "919293970",
                address: "Avenida da Liberdade, 2223",
                email: "catarina.costa@gmail.com",
                check: false,
              },
              {
                photo: "paulMart.png",
                name: "Paulo Martins",
                birthDate: "1983-06-07",
                telNumber: "919293940",
                address: "Rua das Oliveiras, 1617",
                email: "paulo.martins@gmail.com",
                check: false,
              },
              {
                photo: "beSou.png",
                name: "Beatriz Sousa",
                birthDate: "1992-09-12",
                telNumber: "937485960",
                address: "Travessa da Fonte, 1415",
                email: "beatriz.sousa@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
              {
                photo: "fitaAlongamento.png",
                name: "Fita de Alongamento",
                description: "Fita de alongamento de 2 metros",
                quantity: 15,
                check: false,
              },
              {
                photo: "barraCereais.png",
                name: "Barras de Cereal",
                description: "Caixa com 20 barras de cereal",
                quantity: 35,
                check: false,
              },
            ],
            companies: [
              { name: "Prozis", role: "Desporto" },
              { name: "CPYoga", role: "Yoga" },
            ],
            eventFlow:
              "Começamos com uma calorosa receção e uma breve introdução aos princípios do yoga. Em seguida, mergulhamos numa sequência de posturas suaves, respiração consciente e meditação para centrar a mente. Finalizamos com um relaxamento profundo.",
            expectedSuccessRate: 60,
            successRate: 0,
            participantsAssociated: 5,
            costs: 0,
            participants: 0,
            donatives: 0,
            duration: 0,
            feedback: [],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "aulYog.png",
            name: "Gustavo Lima",
            birthDate: "1995-08-20",
            telNumber: "915432789",
            theme: "Sessão de Meditação",
            local: "Lisboa",
            targetAudience: "Adultos",
            minParticipants: 15,
            maxParticipants: 25,
            objective:
              "Oferecer uma sessão de meditação",
            date: "2024-07-15",
            status: "aceite",
            email: "gugalima.43r@gmail.com",
            expectedDuration: "30",
            professionals: [
              {
                name: "Ana Silva",
                role: "Instrutora de Meditação",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "luCost.png",
                name: "Luís Costa",
                birthDate: "1986-04-03",
                telNumber: "932405060",
                address: "Avenida das Árvores, 1213",
                email: "luis.costa@gmail.com",
                check: false,
              },
              {
                photo: "catCos.png",
                name: "Catarina Costa",
                birthDate: "1989-07-22",
                telNumber: "919293970",
                address: "Avenida da Liberdade, 2223",
                email: "catarina.costa@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "fitaAlongamento.png",
                name: "Fita de Alongamento",
                description: "Fita de alongamento de 2 metros",
                quantity: 15,
                check: false,
              },
            ],
            companies: [
              {
                name: "ZenMeditation",
                role: "Meditação",
              },
              {
                name: "HealthyLife",
                role: "Saúde",
              },
            ],
            eventFlow:
              "Iniciaremos com uma breve introdução sobre os benefícios da meditação, seguida por uma série de exercícios de respiração e técnicas de relaxamento. Em seguida, entraremos na meditação guiada, focando na atenção plena e no relaxamento profundo. Finalizaremos com uma partilha de experiências e dicas para integrar a meditação na vida diária.",
            expectedSuccessRate: 80,
            successRate: 0,
            participantsAssociated: 9,
            costs: 0,
            participants: 0,
            donatives: 0,
            duration: 0,
            feedback: [],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "treinoFun.png",
            name: "Luís Silva",
            birthDate: "1987-11-03",
            telNumber: "917654321",
            theme: "Treino Físico",
            local: "Porto",
            targetAudience: "Jovens e Adultos",
            minParticipants: 10,
            maxParticipants: 20,
            objective:
              "Realizar um treino funcional dinâmico",
            date: "2024-03-20",
            status: "passada",
            email: "lmpsilva8@gmail.com",
            expectedDuration: "45",
            professionals: [
              {
                name: "Rita Silva",
                role: "Personal Trainer",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "andSan.png",
                name: "André Santos",
                birthDate: "1988-02-05",
                telNumber: "919293949",
                address: "Travessa dos Cedros, 789",
                email: "andre.santos@gmail.com",
                check: false,
              },
              {
                photo: "joaLop.png",
                name: "Joana Lopes",
                birthDate: "1999-12-19",
                telNumber: "940149282",
                address: "Rua do Sol Nascente",
                email: "joanalopes19@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "fitaAlongamento.png",
                name: "Fita de Alongamento",
                description: "Fita de alongamento de 2 metros",
                quantity: 15,
                check: false,
              },
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
            ],
            companies: [
              {
                name: "FitZone",
                role: "Treino Funcional",
              },
              {
                name: "HealthPeak",
                role: "Saúde",
              },
            ],
            eventFlow:
              "Iniciaremos com uma breve sessão de aquecimento, seguida por uma série de exercícios funcionais que visam fortalecer diferentes grupos musculares. Em seguida, faremos circuitos de treino dinâmicos, utilizando equipamentos simples e movimentos naturais. Finalizaremos com alongamentos e uma sessão de relaxamento para recuperar o corpo e a mente.",
            expectedSuccessRate: 80,
            successRate: 100,
            participantsAssociated: 10,
            costs: 15,
            participants: 13,
            donatives: 20,
            duration: 30,
            feedback: [100, 80],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "aulTen.png",
            name: "Luís Silva",
            birthDate: "1992-06-18",
            telNumber: "919876543",
            theme: "Aula de Tênis",
            local: "Lisboa",
            targetAudience: "Jovens e Adultos",
            minParticipants: 6,
            maxParticipants: 12,
            objective:
              "Oferecer uma aula de tênis para iniciantes",
            date: "2024-08-10",
            status: "aceite",
            email: "lmpsilva8@gmail.com",
            expectedDuration: "60",
            professionals: [
              {
                name: "João Silva",
                role: "Instrutor de Tênis",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "mariOli.png",
                name: "Mariana Oliveira",
                birthDate: "1995-11-10",
                telNumber: "925354647",
                address: "Rua da Praia, 1011",
                email: "mariana.oliveira@gmail.com",
                check: false,
              },
              {
                photo: "ricFer.png",
                name: "Ricardo Fernandes",
                birthDate: "1995-10-18",
                telNumber: "919293960",
                address: "Rua do Sol, 2021",
                email: "ricardo.fernandes@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
              {
                photo: "kit.png",
                name: "Kit de Primeiros Socorros",
                description: "Kit básico para emergências",
                quantity: 8,
                check: false,
              },
            ],
            companies: [
              {
                name: "TennisZone",
                role: "Tênis",
              },
              {
                name: "HealthPeak",
                role: "Saúde",
              },
            ],
            eventFlow:
              "Começaremos com uma breve introdução ao tênis, abordando regras básicas e técnicas fundamentais. Em seguida, realizaremos exercícios de aquecimento e prática de golpes básicos, como forehand e backhand. Depois, faremos atividades de jogo em duplas para aplicar as habilidades aprendidas. Encerraremos com um resumo e dicas para continuar praticando.",
            expectedSuccessRate: 60,
            successRate: 0,
            participantsAssociated: 5,
            costs: 0,
            participants: 0,
            donatives: 0,
            duration: 0,
            feedback: [],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "palestr.png",
            name: "Pedro Almeida",
            birthDate: "1975-09-28",
            telNumber: "919112233",
            theme: "Palestra: Vida Saudável",
            local: "Porto",
            targetAudience: "Adultos",
            minParticipants: 20,
            maxParticipants: 50,
            objective:
              "Realizar uma palestra sobre hábitos saudáveis",
            date: "2024-04-15",
            status: "passada",
            email: "pedro.almeida@gmail.com",
            expectedDuration: "90",
            professionals: [
              {
                name: "Dr. Miguel Torres",
                role: "Médico Nutricionista",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "anaSou.png",
                name: "Ana Sousa",
                birthDate: "2001-11-05",
                telNumber: "923456789",
                address: "Rua das Acácias",
                email: "anasousa01@gmail.com",
                check: false,
              },
              {
                photo: "ruiCos.png",
                name: "Rui Costa",
                birthDate: "2000-04-29",
                telNumber: "938477193",
                address: "Rua das Flores",
                email: "ruicosta2000@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
              {
                photo: "pratosDescartaveis.png",
                name: "Pratos Descartáveis",
                description: "Pacote com 50 pratos descartáveis biodegradáveis",
                quantity: 30,
                check: false,
              },
            ],
            companies: [
              {
                name: "HealthPlus",
                role: "Saúde",
              },
              {
                name: "PharmaVida",
                role: "Farmácia",
              },
            ],
            eventFlow:
              "A palestra começará com uma introdução ao tema da vida saudável e sua importância para a qualidade de vida. O Dr. Miguel Torres apresentará dicas práticas para uma alimentação equilibrada e estilo de vida saudável. Haverá espaço para perguntas e respostas no final.",
            expectedSuccessRate: 80,
            successRate: 100,
            participantsAssociated: 30,
            costs: 22,
            participants: 42,
            donatives: 70,
            duration: 70,
            feedback: [100, 100, 80],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "palestr.png",
            name: "Gustavo Lima",
            birthDate: "1983-12-10",
            telNumber: "919998877",
            theme: "Workshop: A Saúde Mental",
            local: "Lisboa",
            targetAudience: "Todos",
            minParticipants: 15,
            maxParticipants: 30,
            objective:
              "Realizar um workshop para a saúde mental",
            date: "2024-08-20",
            status: "aceite",
            email: "gugalima.43r@gmail.com",
            expectedDuration: "120",
            professionals: [
              {
                name: "Dr. Sofia Carvalho",
                role: "Psicóloga Clínica",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "carPer.png",
                name: "Carlos Pereira",
                birthDate: "1988-03-15",
                telNumber: "912345678",
                address: "Travessa do Mar",
                email: "cpereira88@gmail.com",
                check: false,
              },
              {
                photo: "paulMend.png",
                name: "Paulo Mendes",
                birthDate: "1993-08-30",
                telNumber: "934567890",
                address: "Avenida da Liberdade",
                email: "pmendes93@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
              {
                photo: "pratosDescartaveis.png",
                name: "Pratos Descartáveis",
                description: "Pacote com 50 pratos descartáveis biodegradáveis",
                quantity: 30,
                check: false,
              },
            ],
            companies: [
              {
                name: "Mindfulness Institute",
                role: "Saúde Mental",
              },
              {
                name: "CalmDown",
                role: "Bem-Estar",
              },
            ],
            eventFlow:
              "O workshop terá uma introdução aos conceitos básicos de saúde mental e técnicas de auto-cuidado. Em seguida, a Dra. Sofia Carvalho conduzirá atividades práticas e discussões em grupo sobre estratégias para lidar com o estresse e promover o bem-estar emocional.",
            expectedSuccessRate: 80,
            successRate: 0,
            participantsAssociated: 13,
            costs: 0,
            participants: 0,
            donatives: 0,
            duration: 0,
            feedback: [],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "sessMotiv.png",
            name: "Ana Silva",
            birthDate: "1985-10-15",
            telNumber: "919876543",
            theme: "Sessão Superação",
            local: "Lisboa",
            targetAudience: "Todos",
            minParticipants: 15,
            maxParticipants: 30,
            objective:
              "Realizar uma sessão motivacional",
            date: "2024-08-20",
            status: "aceite",
            email: "ana.silva@gmail.com",
            expectedDuration: "120",
            professionals: [
              {
                name: "Diana Santos",
                role: "Coach de Vida",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "ricFer.png",
                name: "Ricardo Fernandes",
                birthDate: "1995-10-18",
                telNumber: "919293960",
                address: "Rua do Sol, 2021",
                email: "ricardo.fernandes@gmail.com",
                check: false,
              },
              {
                photo: "catCos.png",
                name: "Catarina Costa",
                birthDate: "1989-07-22",
                telNumber: "919293970",
                address: "Avenida da Liberdade, 2223",
                email: "catarina.costa@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
            ],
            companies: [
              {
                name: "Mindset",
                role: "Motivação",
              },
              {
                name: "Sucesso Pessoal",
                role: "Desenvolvimento Pessoal",
              },
            ],
            eventFlow:
              "A sessão motivacional começará com uma introdução ao tema da superação de obstáculos e do desenvolvimento pessoal. Diana Santos compartilhará histórias inspiradoras e estratégias para lidar com desafios. Os participantes terão a oportunidade de refletir e definir metas pessoais para o futuro.",
            expectedSuccessRate: 60,
            successRate: 0,
            participantsAssociated: 10,
            costs: 0,
            participants: 0,
            donatives: 0,
            duration: 0,
            feedback: [],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "sessMotiv.png",
            name: "João Mendonça",
            birthDate: "1980-07-20",
            telNumber: "919223344",
            theme: "Workshop: Mindfulness",
            local: "Porto",
            targetAudience: "Adultos",
            minParticipants: 10,
            maxParticipants: 25,
            objective:
              "Realizar um workshop sobre mindfulness",
            date: "2024-05-10",
            status: "passada",
            email: "joao.mendonca@gmail.com",
            expectedDuration: "90",
            professionals: [
              {
                name: "Sofia Santos",
                role: "Psicóloga Clínica",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "joaLop.png",
                name: "Joana Lopes",
                birthDate: "1999-12-19",
                telNumber: "940149282",
                address: "Rua do Sol Nascente",
                email: "joanalopes19@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
            ],
            companies: [
              {
                name: "Serena",
                role: "Bem-Estar",
              },
              {
                name: "MindfulLife",
                role: "Mindfulness",
              },
            ],
            eventFlow:
              "O workshop sobre mindfulness e bem-estar começará com uma introdução aos conceitos básicos de mindfulness e sua aplicação no dia a dia. Sofia Santos conduzirá exercícios práticos para promover a consciência plena e a redução do stress. Os participantes terão a oportunidade de partilhar experiências e aprender estratégias para melhorar o seu bem-estar emocional.",
            expectedSuccessRate: 100,
            successRate: 80,
            participantsAssociated: 13,
            costs: 9,
            participants: 20,
            donatives: 54,
            duration: 60,
            feedback: [80],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "aulYog.png",
            name: "Ana Ferreira",
            birthDate: "1985-04-15",
            telNumber: "919334455",
            theme: "Sessão de Relaxamento",
            local: "Lisboa",
            targetAudience: "Adultos",
            minParticipants: 15,
            maxParticipants: 30,
            objective:
              "Realizar uma sessão de relaxamento",
            date: "2024-04-20",
            status: "passada",
            email: "ana.ferreira@gmail.com",
            expectedDuration: "60",
            professionals: [
              {
                name: "Marta Pereira",
                role: "Instrutora de Meditação",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "mariOli.png",
                name: "Mariana Oliveira",
                birthDate: "1995-11-10",
                telNumber: "925354647",
                address: "Rua da Praia, 1011",
                email: "mariana.oliveira@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "barraCereais.png",
                name: "Barras de Cereal",
                description: "Caixa com 20 barras de cereal",
                quantity: 35,
                check: false,
              },
              {
                photo: "fitaAlongamento.png",
                name: "Fita de Alongamento",
                description: "Fita de alongamento de 2 metros",
                quantity: 15,
                check: false,
              },
              {
                photo: "cronometro.png",
                name: "Cronômetro",
                description: "Cronômetro digital",
                quantity: 10,
                check: false,
              },
            ],
            companies: [
              {
                name: "Zen",
                role: "Meditação",
              },
              {
                name: "RelaxLife",
                role: "Bem-Estar",
              },
            ],
            eventFlow:
              "A sessão de relaxamento e meditação começará com uma breve introdução aos benefícios da prática da meditação para o bem-estar mental. Marta Pereira guiará os participantes por exercícios de respiração e técnicas de relaxamento. Os participantes serão convidados a praticar a meditação guiada e a refletir sobre as sensações e emoções.",
            expectedSuccessRate: 80,
            successRate: 100,
            participantsAssociated: 13,
            costs: 9,
            participants: 19,
            donatives: 10,
            duration: 50,
            feedback: [100, 100, 80],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          },
          {
            photo: "treinoFun.png",
            name: "Luís Silva",
            birthDate: "1987-11-03",
            telNumber: "917654321",
            theme: "Treino Funcional",
            local: "Porto",
            targetAudience: "Jovens e Adultos",
            minParticipants: 10,
            maxParticipants: 20,
            objective:
              "Realizar um treino funcional",
            date: "2024-05-25",
            status: "passada",
            email: "lmpsilva6@gmail.com",
            expectedDuration: "45",
            professionals: [
              {
                name: "Rita Silva",
                role: "Personal Trainer",
                check: false,
              },
            ],
            collaborators: [
              {
                photo: "andSan.png",
                name: "André Santos",
                birthDate: "1988-02-05",
                telNumber: "919293949",
                address: "Travessa dos Cedros, 789",
                email: "andre.santos@gmail.com",
                check: false,
              },
              {
                photo: "joaLop.png",
                name: "Joana Lopes",
                birthDate: "1999-12-19",
                telNumber: "940149282",
                address: "Rua do Sol Nascente",
                email: "joanalopes19@gmail.com",
                check: false,
              },
            ],
            materials: [
              {
                photo: "fitaAlongamento.png",
                name: "Fita de Alongamento",
                description: "Fita de alongamento de 2 metros",
                quantity: 15,
                check: false,
              },
              {
                photo: "garrafaA.png",
                name: "Garrafa de Água",
                description: "Garrafa de água reutilizável de 0.5L",
                quantity: 30,
                check: false,
              },
            ],
            companies: [
              {
                name: "FitZone",
                role: "Treino Funcional",
              },
              {
                name: "HealthPeak",
                role: "Saúde",
              },
            ],
            eventFlow:
              "Iniciaremos com uma breve sessão de aquecimento, seguida por uma série de exercícios funcionais que visam fortalecer diferentes grupos musculares. Em seguida, faremos circuitos de treino dinâmicos, utilizando equipamentos simples e movimentos naturais. Finalizaremos com alongamentos e uma sessão de relaxamento para recuperar o corpo e a mente.",
            expectedSuccessRate: 80,
            successRate: 100,
            participantsAssociated: 10,
            costs: 15,
            participants: 13,
            donatives: 20,
            duration: 30,
            feedback: [100, 80],
            duringIniciativePhotos: [],
            duringIniciativeVideos: [],
            duringIniciativeTexts: [],
            duringIniciativeAudios: [],
            reportProblem: false,
            problem: "",
          }
        ])
      );
  },
};
</script>